NSWebKDS/Controllers/HomeController.cs
using Newtonsoft.Json;
using NSWebKDS.Shared;
using NSWebKDS.Shared.Factory;
using NSWebKDS.Shared.Models.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSWebKDS.Controllers
{
    public class HomeController : Controller
    {
        private ActivateFactory _fac;
        public HomeController()
        {
            _fac = new ActivateFactory();
        }
        public ActionResult Index()
        {

            //NSLog.Logger.Info("abc....");
            return View();
        }

        [HttpPost]
        public JsonResult Active(ActivateModels model)
        {
            var data = new ActivateStoreModels();
            try
            {
                data = _fac.Activate(model);
                if(data != null && data.ListStore != null && data.ListStore.Any())
                {
                    var ParentStore = data.ListStore.GroupBy(x => new { x.CompanyId, x.CompanyName })
                        .Select(x => new  NSWebKDS.Shared.Models.StoreModels
                        {
                            CompanyId = x.Key.CompanyId,
                            CompanyName = x.Key.CompanyName
                        }).ToList();

                    ParentStore.ForEach(x =>
                    {
                        x.ChildStore = data.ListStore.Where(z => z.CompanyId.Equals(x.CompanyId)).ToList();
                        x.ChildStore.ForEach(o =>
                       {
                           var sExpiryDate = o.ExpiredDate == Commons.MaxDate ? "No expiry dates" : "Expiry Date: " + o.ExpiredDate.ToString("dd/MM/yyyy"); 
                           o.Name = "<div style=\"font-weight:bold;\">" + o.Name+ "</div><div class=\"divsmall\">&nbsp;&nbsp;&nbsp;<small> "+ sExpiryDate + "</small></div>";
                       });
                    });

                    data.ListStore = ParentStore;
                }
                else if(data != null && data.ListStore.Count == 0 && data.Success)
                {
                    // create cookie 
                    HttpCookie ActiveCookies = new HttpCookie("cookiesActive");
                    if(ActiveCookies != null)
                    {
                        ActiveCookies.Expires = DateTime.Now.AddMilliseconds(-1);
                    }
                    string myObjectJson = JsonConvert.SerializeObject(model);
                    ActiveCookies.Value = Server.UrlEncode(myObjectJson);
                    ActiveCookies.Expires = DateTime.MaxValue;
                    HttpContext.Response.Cookies.Add(ActiveCookies);
                }
            }
            catch(Exception ex)
            {
                NSLog.Logger.Error("Active controller", ex);
            }
            return Json(data);
        }

        [HttpGet]
        public void GetSettings()
        {
            if (Request.Cookies["cookiesActive"] != null)
            {
                var activate = Request.Cookies["cookiesActive"];
                var activateDecode = Server.UrlDecode(activate.Value);
                var activateValue = JsonConvert.DeserializeObject<ActivateModels>(activateDecode);

                CommonFunctions.ListenServer();
                CommonFunctions.GetListGeneralSetting(activateValue.StoreId);

                //CommonFunctions.RefreshOrder();
            }
        }
       

    }
}

NSWebKDS/Controllers/OrderManagementController.cs
using Newtonsoft.Json;
using NSWebKDS.Shared;
using NSWebKDS.Shared.Factory;
using NSWebKDS.Shared.Models;
using NSWebKDS.Shared.Models.OrderManagement;
using System;
using System.Linq;
using System.Web.Mvc;


namespace NSWebKDS.Controllers
{
    public class OrderManagementController : Controller
    {
        private OrderManagementFactory _factory = null;

        public OrderManagementController()
        {
            _factory = new OrderManagementFactory();
        }

        // GET: OrderManagement
        public ActionResult Index()
        {
            if (!string.IsNullOrEmpty(Commons._StoreId))
            {
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult GetFilter(OrderManagementClientModels _filterModel)
        {
            OrderManagementApiResponseModels result = new OrderManagementApiResponseModels();
            OrderManagementClientModels filterModel = new OrderManagementClientModels();
            try
            {
                filterModel = _filterModel;
                NSLog.Logger.Info("GetFilter_Request: ", filterModel);
                result = _factory.GetListData(filterModel);
            }
            catch (Exception ex)
            {
                NSLog.Logger.Error("GetFilter_Error: ", ex);
            }
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;// Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetListFilter(string StoreId)
        {
            FilterResponseModel result = new FilterResponseModel();
            FilterFactory _fac = new FilterFactory();
            try
            {
                result.ListTable = _fac.GetListTable(Commons._StoreId, Commons.AppKey, Commons.AppSecret);
                result.ListZone = _fac.GetListZone(Commons._StoreId, Commons.AppKey, Commons.AppSecret);
                result.ListPrinter = _fac.GetListPrinter(Commons._StoreId, Commons.AppKey, Commons.AppSecret);
                if (result.ListZone != null && result.ListZone.Any())
                {
                    result.ListZone = result.ListZone.OrderBy(x => x.Name).ToList();
                }
                if (result.ListTable != null && result.ListTable.Any())
                {
                    result.ListTable = result.ListTable.OrderBy(x => x.Name).ToList();
                }
                if (result.ListPrinter != null && result.ListPrinter.Any())
                {
                    result.ListPrinter = result.ListPrinter.OrderBy(x => x.PrinterName).ToList();
                }
            }
            catch (Exception ex)
            {
                NSLog.Logger.Error("GetListFilter_Error: ", ex);
            }
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;// Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

NSWebKDS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NSWebKDS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NSWebKDS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="background">
    <img src="@Url.Content("~/Content/fonts/Image/background.png")"  />
</div>
<script>
    function filter() {

    }
</script>

NSWebKDS/Views/OrderManagement/Index.cshtml
@{
    ViewBag.Title = "Order Management";
}
<div id="divListOrder" class="animate-bottom" style="width:100%; padding:0; display:none;" ng-controller="ordermanagementCtrl">
    <div class="bodyContent">
        <div id="List" >
            @*Header*@
            <div class="row header text-uppercase height-50 font-weight-bold col-lg-12" style="padding-top:0px; position:fixed; top:104px; z-index:9998; background-color:#fff; margin-right:0px; margin-left:0px;">
                <div class="col-lg-1 col-md-1"></div>
                <div class="col col-lg-1 text-center col-md-1" style="padding:0">
                    Time
                </div>
                <div class="col col-lg-2 text-center col-md-2">
                    Qty
                </div>
                <div class="col col-lg-8 col-md-8">
                    Dishes
                </div>
            </div>

            @*ListOrder*@
            <div class="row" style="margin-top:170px; width:100%;"> </div>
            <div class="row" ng-repeat="order in orderResponse track by order.IdOrderNo" id="{{order.IdOrderNo}}" emit-last-repeater-element-order style="margin-right:0px; margin-left:0px;">

                @*/row - Order*@
                <div class="row height-40 bg-order-table font-weight-bold col-lg-12"
                     id="_{{order.IdOrderNo}}" name="{{order.DeliveryTime}}" style="margin-right:0px; margin-left:0px; width:100%;">
                    <div class="col col-lg-12">
                        {{order.OrderNo}}
                    </div>
                </div>

                @*/row - Item*@
                <div class="row height-50 bg-dish col-lg-12 rowTimer itemTag"
                     ng-repeat="item in order.ListItem"
                     id="{{item.ID}}"
                     data-time="{{item.DataTime}}"                   
                     data-orderno="{{order.IdOrderNo}}"
                     style="background-color: {{item.bgColor}}; color: {{item.Color}}; margin-right:0px; margin-left:0px;">
                    <div class="col col-lg-1 text-right col-md-1">
                        <img src="~/Content/fonts/Image/notice.png" ng-if="item.IsDel == true" width="25" class="content-center" />
                    </div>
                    <div class="col col-lg-1 col-md-1">
                        <span class="content-center">{{item.Time}}</span>
                    </div>
                    <div class="col col-lg-2 col-md-2 text-center">
                        <span class="content-center">{{item.Qty}}</span>
                    </div>
                    <div class="col col-lg-5 col-md-4">
                        <span ng-bind-html="renderHtml(item.Name)"></span>
                    </div>
                    <div class="col col-lg-1 col-md-1 text-right">
                        <img src="~/Content/fonts/Image/takeaway.png" ng-if="item.IsTA == true" width="70" class="content-center" />
                    </div>
                    <div class="col col-lg-2 col-md-3 text-uppercase" ng-class="item.IsDel == true ? '' : 'pending'">
                        <span class="content-center">
                            Pending
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div id="Gird">
            <div id="parenGrid">
                <div class="gird" ng-repeat="gird in listGird track by $index" emit-last-repeater-element-order-grid>
                    <div id="item_{{item.IdOrderNo}}" class="gridTime item"
                         ng-repeat="item in gird track by $index"
                         data-lapseTime="{{item.LapseTime}}"
                         data-orderno="{{item.IdOrderNo}}">
                        <div id="_gird_{{item.IdOrderNo}}" class="col-md-12 head-gird bg-order-gird"  name="{{item.DeliveryTime}}">
                            <div style="height:40px;padding:0 15px">
                                <div class="left-50">
                                    Tag: <span>{{item.TagNumber}}</span>
                                </div>
                                <div class="left-50">
                                    Order No: <span>{{item.IdOrderNo.substr(-3)}} </span>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div style="height:35px; padding:0 15px">
                                <div class="left-50">
                                    Order Time: <span>{{item.OrderTime}}</span>
                                </div>
                                <div class="left-50">
                                    Time Lapse: <span id="_timeSlap_{{item.IdOrderNo}}" style="min-width:115px">00:00:00
                                    </span>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="col-md-12 head-item bg-head bg-head_{{item.IdOrderNo}}" >
                            <div class="fleft" style="width:20%;">Qty</div>
                            <div class="fleft" style="width:20%;">Item</div>
                            <div class="fleft" style="width:60%;">
                                <div ng-if="item.DeliveryType == -1" style="float:right">
                                    <div ng-if="item.IsTA == true">
                                        <img src="~/Content/fonts/Image/takeaway120.png" width="35" class="content-center" />
                                        <span class="text-uppercase" style="color:#9e27ba">take away</span>
                                    </div>
                                    <div ng-if="item.IsTA == false">
                                        <img src="~/Content/fonts/Image/eatin120.png" width="35" class="content-center" />
                                        <span class="text-uppercase" style="color:#1d9325">eat in</span>
                                    </div>
                                </div>                                
                                <div ng-if="item.DeliveryType == 1" style="float:right">
                                    <img src="~/Content/fonts/Image/Deli120.png" width="35" class="content-center" />
                                    <span class="text-uppercase" style="color:#ec008c">deliver at: {{item.DeliveryTime}}</span>
                                </div>
                                <div ng-if="item.DeliveryType == 2" style="float:right">
                                    <img src="~/Content/fonts/Image/pickup120.png" width="35" class="content-center" />
                                    <span class="text-uppercase" style="color:#f7941e">Pickup at: {{item.DeliveryTime}}</span>
                                </div>                              
                            </div>
                        </div>
                        <div class="clearfix bg-head"></div>
                        <div id="item_grid_{{item.IdOrderNo}}" class="list-item-grid ">
                            <div class="col-md-12" ng-repeat="oder in item.ListItem" style="background-color: {{oder.bgColor}}; color: {{oder.Color}}; margin-top:1px;  font-family: 'SF Text';">
                                <div class="fleft" style="width:20%; ">{{oder.Qty}}</div>
                                <div class="fleft" style="width:65%;">
                                    <div ng-if="oder.Set==''">
                                        {{oder.GName}}
                                        <ul style="margin-left:25px;">
                                            <li style="list-style-type: disc;" ng-repeat="d in oder.ListItem track by $index"><span> {{d}}</span></li>
                                        </ul>
                                    </div>

                                    <div ng-if="oder.Set!=''">
                                        {{oder.Set}}
                                        <ul style="margin-left:25px;">
                                            <li style="list-style-type: disc;">
                                                <span>  {{oder.GName}} </span>
                                                <ul style="margin-left:25px;">
                                                    <li style="list-style-type: circle;" ng-repeat="d in oder.ListItem track by $index"><span> {{d}}</span></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="fleft" style="width:10%">
                                    <img src="~/Content/fonts/Image/takeaway.png" ng-if="oder.IsTA == true" width="25" class="content-center" />
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>                           
                    </div>
                </div>         
            </div>           
        </div>
    </div>
</div>

<script>
    $(function () {
        var scope = angular.element(document.getElementById('divListOrder')).scope();
        setInterval(function () {       
            scope.countTime();
        }, 1000);
        setInterval(function () {
            scope.changeColor();
        }, 10000);
    });
    function filter() {
        $("#item").toggleClass('over-right');
    }
    $('.navs').mousedown(function (event) {
        if (!$("#item").hasClass('over-right')) {
            filter();
        }
    });
    $('.bodyContent').mousedown(function (event) {
        if (!$("#item").hasClass('over-right')) {
            filter();
        }
    });
    //set width height for gird
    var heightitem = _columnGird / 3;
    var width = $(window).width();
    var height = $(window).height();
    $(".gird").css({ 'width': width - 5 + 'px', 'height': height - 163 + 'px' });
    $(".item").css({ 'width': (width - 15) / 3 + 'px', 'height': (height - 172) / heightitem + (heightitem == 1 ? 2 : 0) + 'px' });
    $(window).resize(function () {
        //set width height for gird when resize screen
        var width = $(window).width();
        var height = $(window).height();
        var countItem = this.document.getElementsByClassName("gird").length;
        $("#parenGrid").css({ 'width': countItem * (width-4) + 'px', 'height': height - 158 + 'px'  });
        $(".gird").css({ 'width': width - 5 + 'px', 'height': height - 163 + 'px' });
        $(".item").css({ 'width': (width - 15) / 3 + 'px', 'height': (height - 172) / heightitem + (heightitem == 1 ? 2 : 0) + 'px' });
        var $mvar = $('.gridTime');
        for (i = 0; i < $mvar.length; i++) {
            var _OrderNo = $mvar.eq(i).data("orderno");
            // set height for div item (scroll)
            var parentHeight = $('#item_' + _OrderNo).height();
            var headHeight = $('#_gird_' + _OrderNo).height() + $('.bg-head_' + _OrderNo).height();
            $("#item_grid_" + _OrderNo).css({ 'height': parentHeight - headHeight + 'px' });
        }
    });
</script>

NSWebKDS/Views/Shared/_Layout.cshtml
@using NSWebKDS.Shared

<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script>
    @{
        string controller = this.ViewContext.RouteData.Values["controller"].ToString();
        string baseUrl = new Uri(Request.Url, Url.Content("~")).ToString();
    }
    ControllerName = "@controller";
        BaseUrl = "@baseUrl";
        var _RedirectToActionMana = '@Url.Action("Index", "OrderManagement")';
        var _HostApiActive = '@Url.Action("Active", "Home")';
        var _HostApiGetSettings = '@Url.Action("GetSettings","Home")';
        var _HostApiGetFilter = '@Url.Action("GetFilter", "OrderManagement")';
        var _HostApiGetListFilter = '@Url.Action("GetListFilter", "OrderManagement")';

    var _Sound = BaseUrl + "@Commons._soundPrepareScreen";
    var _PendingTime = "@Commons._pendingTime";
    var _HostApiUrl = "@Commons.HostApiUrl";
    var _StoreId = "@Commons._StoreId";
    var _AppKey = "@Commons.AppKey";
        var _AppSecret = "@Commons.AppSecret";
        var socketUrl = "@Commons.SocketUrl";
        var _columnGird = "@Commons._numOfCellOrderMana";
    </script>
</head>
<body>
    <div id="loader"></div>
    <div>
        @Scripts.Render("~/sk")
        @Scripts.Render("~/ng")
        @Scripts.Render("~/app")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")

        @Html.Partial("_Nav")
        <div class="parent">

            @Html.Partial("_Filter")
            @RenderBody()

            <div ng-controller="homeCtrl">
                <div class="modal fade" id="activateModalStep1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Activate</h5>
                            </div>
                            <div class="modal-body">
                                <div class="step1" ng-show="IsStep1">
                                    <form name="myFormStep1" id="myFormStep1">
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-xl-12">
                                                <input class="form-control" ng-model="URL" name="URL" placeholder="URL" style="border-radius:0rem !important;" required />
                                                <span style="color:red" ng-show="myFormStep1.URL.$dirty && myFormStep1.URL.$invalid">
                                                    <label ng-show="myFormStep1.URL.$error.required">URL is required.</label>
                                                </span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-xl-12">
                                                <input type="email" class="form-control" ng-model="Email" name="Email" id="txtEmail" placeholder="Email" autocomplete="off" required style="border-radius:0rem !important;" />
                                                <span style="color:red" ng-show="myFormStep1.Email.$dirty && myFormStep1.Email.$invalid">
                                                    <label ng-show="myFormStep1.Email.$error.required">Email is required.</label>
                                                    <label ng-show="myFormStep1.Email.$error.email">E-mail is not valid.</label>
                                                </span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-xl-12">
                                                <input type="hidden" ng-model="AppSecret" />
                                                <input type="hidden" ng-model="AppKey" />
                                                <input class="form-control" type="password" name="Password" ng-model="Password" placeholder="Password" autocomplete="off" required style="border-radius:0rem !important;" />
                                                <span style="color:red" ng-show="myFormStep1.Password.$dirty && myFormStep1.Password.$invalid">
                                                    <label ng-show="myFormStep1.Password.$error.required">Password is required.</label>
                                                </span>
                                            </div>
                                        </div>

                                        <div class="form-group" ng-show="IsShowStep1">
                                            <div class="col-md-12 col-sm-12 col-xl-12">
                                                <span style="color:red">
                                                    <label>{{MessageStep1}}.</label>
                                                </span>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <div class="step2" ng-show="IsStep2">
                                    <form name="myFormStep2">
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-xl-12">
                                                <input class="form-control" ng-model="ApproveCode" name="ApproveCode" placeholder="License Key" autocomplete="off" required style="font-family:SF Text Semibold;font-size:24pt; color:#B3B3B3;border-radius:0rem !important;" />
                                                <span style="color:red" ng-show="myFormStep2.ApproveCode.$dirty && myFormStep2.ApproveCode.$invalid">
                                                    <label ng-show="myFormStep2.ApproveCode.$error.required">License Key is required.</label>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label col-md-12 col-sm-12 col-xs-12 lineHeight" style="font-family: SF Text Semibold;font-size: 24pt;color: #B3B3B3 !important;margin-bottom:-10px;">Change Location</label>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12 col-sm-12 col-xl-12">

                                                <select class="form-control" ng-model="Id" id="myLocation" name="Id" style="width:100% !important;height:100px !important;" required>
                                                    <option></option>
                                                    <optgroup ng-repeat="item in ListStore" label="{{item.CompanyName}}">
                                                        <option ng-repeat="itemChild in item.ChildStore" value="{{itemChild.Id}}">
                                                            {{itemChild.Name}}
                                                        </option>
                                                    </optgroup>

                                                </select>
                                                <span style="color:red" ng-show="IsShowStore">
                                                    <label ng-show="IsShowStore">Store is required.</label>
                                                </span>
                                                @*<span style="color:red" ng-show="myFormStep2.Id.$dirty && myFormStep2.Id.$invalid">
                                                    <label ng-show="myFormStep2.Id.$error.required">Store is required.</label>
                                                </span>*@
                                            </div>
                                        </div>

                                        <div class="form-group" ng-show="IsShowStep2">
                                            <div class="col-md-12 col-sm-12 col-xl-12">
                                                <span style="color:red">
                                                    <label>{{MessageStep2}}.</label>
                                                </span>
                                            </div>
                                        </div>

                                    </form>
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal" style="font-weight:bold;width:100px;">CANCEL</button>
                                <button type="button" style="background-color:#9733ee;font-weight:bold;border:none;width:100px;" class="btn btn-primary step1" ng-show="IsStep1" ng-click="fnNextStep();" ng-disabled="myFormStep1.Email.$invalid || myFormStep1.Password.$invalid || myFormStep1.URL.$invalid">NEXT</button>
                                <button type="button" style="background-color:#9733ee;font-weight:bold;border:none;width:100px;" class="btn btn-primary step2" ng-show="IsStep2" ng-click="fnActivate();" ng-disabled="myFormStep2.ApproveCode.$invalid">ACTIVATE</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="loader"></div>
            </div>
        </div>

        <hr />
        <footer>
            <p style="margin-left:20px"><strong>&copy; @DateTime.Now.Year.ToString() <a href="http://www.newstead.com.sg/" target="_blank">Newstead Technologies Pte. Ltd.</a></strong> All rights reserved.</p>
        </footer>
    </div>
</body>
</html>
<script>
    function ShowModalActive() {
        $('#activateModalStep1').modal({
            backdrop: 'static',
            keyboard: false
        });
        setTimeout(function () {
            $('#myFormStep1').trigger("reset");
        }, 500);
    }

    function format(state) {
        if (!state.id) return state.text; // optgroup
        return state.text;
    }

    $(document).ready(function () {
        $("#myLocation").select2({
            placeholder: "Select Location",
            formatResult: format,
            formatSelection: format,
            escapeMarkup: function (m) {
                return m;
            },
        });
        setTimeout(function () {
            $('#myFormStep1').trigger("reset");
        }, 500);
    });
</script>